### ISSUE TITLE
看到了服务提供者，请问是支持引入 laravel 的 ServiceProvider 吗

### ISSUE THREAD

**Issue by mouyong** [ifui/webman-module#1]
期待和作者进行经验交流，微信 MTI1NDA3NTkyMQ==
来源：webman-module

**Comment by mouyong** [comment]
我们也做了一个插件管理器: https://gitee.com/fresns/plugin-manager

是基于 laravel 的

**Comment by mouyong** [comment]
这个插件管理器的一个插件示例：https://github.com/mouyong/laravel-qiniu

**Comment by mouyong** [comment]
查找目录的注册方式，不便于应用插件直接发版到 packagist 上，使用外部主动注册的方式可以解决这个问题。

**Comment by ifui** [comment]
目前是不支持直接引入 Laravel 的 ServiceProvider，但是可以在里面注册插件启动时需要的操作。

**Comment by ifui** [comment]
> 查找目录的注册方式，不便于应用插件直接发版到 packagist 上，使用外部主动注册的方式可以解决这个问题。

其实 webman 官方已经有了可以发布在 packagist 的插件，这个插件生成的模块更适用于放在 github 之类的版本管理系统上，需要的时候更新即可。

**Comment by ifui** [comment]
> 期待和作者进行经验交流，微信 MTI1NDA3NTkyMQ== 来源：webman-module

加你了。
