### ISSUE TITLE
安装的时候报错了

### ISSUE THREAD

**Issue by 2494911084** [ifui/webman-module#2]
![image](https://user-images.githubusercontent.com/29133710/185724086-c3ca5275-abc7-44cb-a4e3-431e3544c41e.png)

**Comment by ifui** [comment]
1.0.0 需要的 php 8 版本，稍后更新的 1.0.1 版会降低依赖php版本的要求（最低参考 webman 1.4 版本为 php >= 7.2）

**Comment by ifui** [comment]
版本已更新，请重新执行 `composer require ifui/webman-module --dev -W`
